### ISSUE TITLE
Page Responsiveness

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/YouTube-Ads-Clone#1]
### What happened?

The page isn't responsive for the mobile devices.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Open website in responsive mode or in any mobile device.
4. See error.
```

### Expected behavior

It should be responsive.

### Version

1.0.3 (Edge)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Browsers (If not available above)

Samsung Internet Browser

### Additional context

The error can be seen on any of the browser and version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GamingCapital** [comment]
Can you assign this issue to me ?

**Comment by AyushAgnihotri2025** [comment]
Ok you can work on it.... @GamingCapital
