### ISSUE TITLE
Improving the button by adding hover effects to it

### ISSUE THREAD

**Issue by Janhvi52** [AyushAgnihotri2025/YouTube-Ads-Clone#11]
### Is your feature request related to a problem? Please describe.

i want to improve the ui and make it look more fascinating by adding some cool hover effects to the buttons!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomilRathore01** [comment]
Hey @Janhvi52 can you please assign this task to me for competing at KWOC 2022.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Janhvi52  ....

**Comment by somya-kr** [comment]
@AyushAgnihotri2025 assign this task to me as well.

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @somya-kr ....

**Comment by Ankita0125** [comment]
hey can you assign this task to me @AyushAgnihotri2025

**Comment by AyushAgnihotri2025** [comment]
@Ankita0125 Sorry but the task is being already completed by @somya-kr in #13

**Comment by AyushAgnihotri2025** [comment]
Completed #13
