### ISSUE TITLE
Adding neon effect on button 

### ISSUE THREAD

**Issue by NiharikaSharma18** [AyushAgnihotri2025/YouTube-Ads-Clone#12]
### Is your feature request related to a problem? Please describe.

As we can see that the button of the page is very simple .
I will add neon effect on it to make it more attractive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomilRathore01** [comment]
Hey @NiharikaSharma18 can you please assign this task to me for competing at KWOC 2022.

**Comment by NiharikaSharma18** [comment]
I'm a contributor in this project nt a mentor

**Comment by SomilRathore01** [comment]
Oh sorry @NiharikaSharma18 , @AyushAgnihotri2025 can you assign this prjct to me for KWOC 2022

**Comment by NiharikaSharma18** [comment]
@AyushAgnihotri2025  plz assign this work to me so that i can work on it

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @NiharikaSharma18 ....

**Comment by AyushAgnihotri2025** [comment]
Ok you can also work 👍 on it @SomilRathore01 ....

**Comment by Ankita0125** [comment]
hey can you assign this task to me @AyushAgnihotri2025

**Comment by NiharikaSharma18** [comment]
i'm already done with the task only ,pushing of file is left

**Comment by NiharikaSharma18** [comment]
Sir,i have pushed the file and kindly review nd merge it

**Comment by AyushAgnihotri2025** [comment]
Completed #17
