### ISSUE TITLE
Look Enhancement

### ISSUE THREAD

**Issue by AyushAgnihotri2025** [AyushAgnihotri2025/YouTube-Ads-Clone#2]
### Is your feature request related to a problem? Please describe.

It's look has to be more enhanced.

### Additional context

Anyone interested can work on it further.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Riya14-dangra** [comment]
hello @AyushAgnihotri2025 Can you please assign me this issue  under kwoc2022 I want to change the look of website??

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Riya14-dangra .....

**Comment by AyushAgnihotri2025** [comment]
Please join our discord for further discussions regarding it.

**Link :** https://discord.gg/Awd3y7m9

**And kindly refer to this once also :** https://bit.ly/3XYy1D4

**Comment by AyushAgnihotri2025** [comment]
Completed #5
