### ISSUE TITLE
login page for user

### ISSUE THREAD

**Issue by Riya14-dangra** [AyushAgnihotri2025/YouTube-Ads-Clone#6]
### Is your feature request related to a problem? Please describe.

A user can come to use you web so each user have a login in it .firstly to have to signup with complete details and then login anytime

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Riya14-dangra** [comment]
> ### Is your feature request related to a problem? Please describe.
> A user can come to use you web so each user have a login in it .firstly to have to signup with complete details and then login anytime
> 
> ### Describe the solution you'd like
> _No response_
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

@AyushAgnihotri2025 can you please assign this issue to me I want to work on it under kwoc2022

**Comment by Riya14-dangra** [comment]
@AyushAgnihotri2025 can you please assign this issue to me I want to work on it under kwoc2022

> > ### Is your feature request related to a problem? Please describe.
> > A user can come to use you web so each user have a login in it .firstly to have to signup with complete details and then login anytime
> > ### Describe the solution you'd like
> > _No response_
> > ### Describe alternatives you've considered
> > _No response_
> > ### Additional context
> > _No response_
> > ### Code of Conduct
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> 
> @AyushAgnihotri2025 can you please assign this issue to me I want to work on it under kwoc2022

**Comment by Riya14-dangra** [comment]
@AyushAgnihotri2025 can you please assign this issue to me I want to work on it under kwoc2022

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Riya14-dangra .....
