### ISSUE TITLE
Add a preloader to the website

### ISSUE THREAD

**Issue by Janhvi52** [AyushAgnihotri2025/YouTube-Ads-Clone#9]
### Is your feature request related to a problem? Please describe.

Since the page loading time is more ,the users have to see a black screen in front of them while the page loads
to avoid this, i want to add a fascinating preloader to the website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AyushAgnihotri2025** [comment]
Ok you can work 👍 on it @Janhvi52 .....
